services:
  app:
    build: .
    container_name: wa-bot
    restart: always
    working_dir: /app
    volumes:
      - .:/app
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8003:80"
    depends_on:
      - php-fpm
    networks:
      - wa-bot_network

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile.php-fpm
    container_name: php-fpm-wa-bot
    volumes:
      - .:/app
    networks:
      - wa-bot_network

  redis:
    image: redis:alpine
    container_name: redis-wa-bot
    ports:
      - "6381:6381"
    networks:
      - wa-bot_network

networks:
  wa-bot_network:
    driver: bridge
# networks:
#   wa-bot_network:
#     external: true
  