FROM php:8.2-fpm

ENV TZ=Asia/Jakarta
RUN apt-get update && apt-get install -y \
    libicu-dev zip unzip git libzip-dev \
    && docker-php-ext-install mysqli intl pdo pdo_mysql zip opcache

RUN pecl install redis && docker-php-ext-enable redis


COPY php.ini /usr/local/etc/php/php.ini

WORKDIR /app
RUN mkdir -p /app/writable && chown -R www-data:www-data /app/writable
USER www-data
